### ISSUE TITLE
Ambiente Lavarel

### ISSUE THREAD

**Issue by lilialnas** [alinevenceslau/livrariadagenteup#9]
Ajustes e configurações que devem ser realizados para iniciar o projeto em Laravel
Essa EPIC obrigatoriamente será quebrada em várias histórias técnicas ou spikes.

**Comment by alinevenceslau** [comment]
Projeto startado.
Segue o commit:
https://github.com/alinevenceslau/livrariadagenteup/commit/7c6ac863b9e7661d6c282b2453856abbe92e140b
